/**
 * Generate Daily Report
 * 
 * Creates a markdown summary of uptime statistics.
 * Output to stdout for use in GitHub Actions.
 */

const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Error: SUPABASE_URL and SUPABASE_SERVICE_KEY required');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function generateReport() {
  const now = new Date();
  const yesterday = new Date(now - 24 * 60 * 60 * 1000);
  
  // Get current status
  const { data: sites, error: sitesError } = await supabase
    .from('site_status_detailed')
    .select('*')
    .order('country');
  
  if (sitesError) throw sitesError;
  
  // Calculate statistics
  const total = sites.length;
  const up = sites.filter(s => s.current_status === true).length;
  const down = sites.filter(s => s.current_status === false).length;
  const unknown = sites.filter(s => s.current_status === null).length;
  
  const avgUptime24h = sites
    .filter(s => s.uptime_24h !== null)
    .reduce((sum, s) => sum + parseFloat(s.uptime_24h), 0) / 
    sites.filter(s => s.uptime_24h !== null).length;
  
  const avgUptime7d = sites
    .filter(s => s.uptime_7d !== null)
    .reduce((sum, s) => sum + parseFloat(s.uptime_7d), 0) / 
    sites.filter(s => s.uptime_7d !== null).length;
  
  // Group by region
  const byRegion = {};
  sites.forEach(site => {
    if (!byRegion[site.region]) {
      byRegion[site.region] = { total: 0, up: 0, down: 0 };
    }
    byRegion[site.region].total++;
    if (site.current_status === true) byRegion[site.region].up++;
    if (site.current_status === false) byRegion[site.region].down++;
  });
  
  // Get sites with issues
  const downSites = sites.filter(s => s.current_status === false);
  const lowUptime = sites
    .filter(s => s.uptime_7d !== null && parseFloat(s.uptime_7d) < 90)
    .sort((a, b) => parseFloat(a.uptime_7d) - parseFloat(b.uptime_7d));
  
  // Generate markdown report
  const report = `# NSO Uptime Report

**Generated:** ${now.toISOString()}  
**Period:** Last 24 hours

---

## Summary

| Metric | Value |
|--------|-------|
| Total Sites | ${total} |
| Currently Up | ${up} (${((up/total)*100).toFixed(1)}%) |
| Currently Down | ${down} |
| Unknown | ${unknown} |
| Avg Uptime (24h) | ${avgUptime24h.toFixed(2)}% |
| Avg Uptime (7d) | ${avgUptime7d.toFixed(2)}% |

---

## By Region

| Region | Sites | Up | Down | Uptime |
|--------|-------|-----|------|--------|
${Object.entries(byRegion)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([region, stats]) => 
    `| ${region} | ${stats.total} | ${stats.up} | ${stats.down} | ${((stats.up/stats.total)*100).toFixed(1)}% |`
  ).join('\n')}

---

## Currently Down Sites

${downSites.length === 0 ? '✅ All sites operational!' : 
downSites.map(s => `- **${s.country}** - ${s.organization}
  - URL: ${s.url}
  - Error: ${s.error_message || 'Unknown'}
  - Last checked: ${s.last_checked}`).join('\n\n')}

---

## Sites with Low Uptime (< 90% over 7 days)

${lowUptime.length === 0 ? '✅ All sites above 90% uptime!' :
lowUptime.slice(0, 20).map(s => 
  `- **${s.country}** - ${s.uptime_7d}% (${s.url})`
).join('\n')}
${lowUptime.length > 20 ? `\n*...and ${lowUptime.length - 20} more*` : ''}

---

## Notes

- Checks run hourly via GitHub Actions
- "Up" means HTTP status 200-399 within 30s timeout
- Data retained for 90 days

Report generated by [NSO Uptime Monitor](https://github.com/opendatawatch/nso-uptime-monitor)
`;

  console.log(report);
}

generateReport().catch(err => {
  console.error('Error generating report:', err);
  process.exit(1);
});
