/**
 * Generate Daily Report
 *
 * Creates a markdown summary of uptime statistics.
 * Output to stdout for use in GitHub Actions.
 */

const { supabase } = require('../src/supabase');
const { calculateStats, groupByRegion } = require('../src/utils/stats');

async function generateReport() {
  const now = new Date();

  // Get current status
  const { data: sites, error: sitesError } = await supabase
    .from('site_status_detailed')
    .select('*')
    .order('country');

  if (sitesError) throw sitesError;

  // Calculate statistics
  const stats = calculateStats(sites);
  const byRegion = groupByRegion(sites);

  // Get sites with issues
  const downSites = sites.filter(s => s.current_status === false);
  const lowUptime = sites
    .filter(s => s.uptime_7d !== null && parseFloat(s.uptime_7d) < 90)
    .sort((a, b) => parseFloat(a.uptime_7d) - parseFloat(b.uptime_7d));

  // Generate markdown report
  const report = `# NSO Uptime Report

**Generated:** ${now.toISOString()}
**Period:** Last 24 hours

---

## Summary

| Metric | Value |
|--------|-------|
| Total Sites | ${stats.total} |
| Currently Up | ${stats.up} (${((stats.up/stats.total)*100).toFixed(1)}%) |
| Currently Down | ${stats.down} |
| Unknown | ${stats.unknown} |
| Avg Uptime (24h) | ${stats.avgUptime24h.toFixed(2)}% |
| Avg Uptime (7d) | ${stats.avgUptime7d.toFixed(2)}% |

---

## By Region

| Region | Sites | Up | Down | Uptime |
|--------|-------|-----|------|--------|
${Object.entries(byRegion)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([region, regionStats]) =>
    `| ${region} | ${regionStats.total} | ${regionStats.up} | ${regionStats.down} | ${((regionStats.up/regionStats.total)*100).toFixed(1)}% |`
  ).join('\n')}

---

## Currently Down Sites

${downSites.length === 0 ? '✅ All sites operational!' :
downSites.map(s => `- **${s.country}** - ${s.organization}
  - URL: ${s.url}
  - Error: ${s.error_message || 'Unknown'}
  - Last checked: ${s.last_checked}`).join('\n\n')}

---

## Sites with Low Uptime (< 90% over 7 days)

${lowUptime.length === 0 ? '✅ All sites above 90% uptime!' :
lowUptime.slice(0, 20).map(s =>
  `- **${s.country}** - ${s.uptime_7d}% (${s.url})`
).join('\n')}
${lowUptime.length > 20 ? `\n*...and ${lowUptime.length - 20} more*` : ''}

---

## Notes

- Checks run hourly via GitHub Actions
- "Up" means HTTP status 200-399 within 30s timeout
- Data retained for 90 days

Report generated by [NSO Uptime Monitor](https://github.com/opendatawatch/nso-uptime-monitor)
`;

  console.log(report);
}

// Run if executed directly (not imported as module)
if (require.main === module) {
  generateReport().catch(err => {
    console.error('Error generating report:', err);
    process.exit(1);
  });
}
